/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedWorkspacesWorkspaceIdRouteRouteImport } from './routes/_authenticated/workspaces/$workspaceId/route'
import { Route as AuthenticatedWorkspacesWorkspaceIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRouteImport } from './routes/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/route'
import { Route as AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRouteImport } from './routes/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId'
import { Route as AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/index'
import { Route as AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdDocumentIdEditRouteImport } from './routes/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId.$documentId.edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdRouteRoute =
  AuthenticatedWorkspacesWorkspaceIdRouteRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRoute =
  AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRouteImport.update(
    {
      id: '/manuscripts/$manuscriptId',
      path: '/manuscripts/$manuscriptId',
      getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdRouteRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRoute =
  AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRouteImport.update(
    {
      id: '/chapters/$chapterId',
      path: '/chapters/$chapterId',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdDocumentIdEditRoute =
  AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdDocumentIdEditRouteImport.update(
    {
      id: '/$documentId/edit',
      path: '/$documentId/edit',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/manuscripts/$manuscriptId': typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRouteWithChildren
  '/workspaces/$workspaceId/manuscripts/$manuscriptId/': typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdIndexRoute
  '/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId': typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRouteWithChildren
  '/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/': typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdIndexRoute
  '/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/$documentId/edit': typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdDocumentIdEditRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/manuscripts/$manuscriptId': typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdIndexRoute
  '/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId': typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdIndexRoute
  '/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/$documentId/edit': typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdDocumentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId': typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/': typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdIndexRoute
  '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId': typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/': typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdIndexRoute
  '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/$documentId/edit': typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdDocumentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/workspaces/$workspaceId'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/help-center'
    | '/settings/'
    | '/users'
    | '/workspaces'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/manuscripts/$manuscriptId'
    | '/workspaces/$workspaceId/manuscripts/$manuscriptId/'
    | '/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId'
    | '/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/'
    | '/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/$documentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/help-center'
    | '/settings'
    | '/users'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/manuscripts/$manuscriptId'
    | '/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId'
    | '/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/$documentId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/workspaces/$workspaceId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/workspaces/'
    | '/_authenticated/workspaces/$workspaceId/'
    | '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId'
    | '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/'
    | '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId'
    | '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/'
    | '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/$documentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspaces/$workspaceId': {
      id: '/_authenticated/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspaces/$workspaceId/': {
      id: '/_authenticated/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdRouteRoute
    }
    '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId': {
      id: '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId'
      path: '/manuscripts/$manuscriptId'
      fullPath: '/workspaces/$workspaceId/manuscripts/$manuscriptId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdRouteRoute
    }
    '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/': {
      id: '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/manuscripts/$manuscriptId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRoute
    }
    '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId': {
      id: '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRoute
    }
    '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/': {
      id: '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRoute
    }
    '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/$documentId/edit': {
      id: '/_authenticated/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/$documentId/edit'
      path: '/$documentId/edit'
      fullPath: '/workspaces/$workspaceId/manuscripts/$manuscriptId/chapters/$chapterId/$documentId/edit'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdDocumentIdEditRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdIndexRoute
  AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdDocumentIdEditRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdDocumentIdEditRoute
}

const AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRouteChildren: AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdIndexRoute,
    AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdDocumentIdEditRoute:
      AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdDocumentIdEditRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdIndexRoute
  AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRouteWithChildren
}

const AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRouteChildren: AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdIndexRoute,
    AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRoute:
      AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdChaptersChapterIdRouteWithChildren,
  }

const AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdRouteRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRoute: typeof AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRouteWithChildren
}

const AuthenticatedWorkspacesWorkspaceIdRouteRouteChildren: AuthenticatedWorkspacesWorkspaceIdRouteRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdIndexRoute:
      AuthenticatedWorkspacesWorkspaceIdIndexRoute,
    AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRoute:
      AuthenticatedWorkspacesWorkspaceIdManuscriptsManuscriptIdRouteRouteWithChildren,
  }

const AuthenticatedWorkspacesWorkspaceIdRouteRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdRouteRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedWorkspacesWorkspaceIdRouteRoute: typeof AuthenticatedWorkspacesWorkspaceIdRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedWorkspacesWorkspaceIdRouteRoute:
    AuthenticatedWorkspacesWorkspaceIdRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
